name: Create UPM branches and run NPM publish

on:
  push:
    tags:
      - v*

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tag name
        id: tag
        run: echo ::set-output name=name::${GITHUB_REF#refs/tags/v}

      - name: Create UPM branches
        uses: hecomi/create-upm-branch-action@main
        with:
          git-tag: ${{steps.tag.outputs.name}}
          pkg-root-dir-path: Assets/uOSC
          main-branch: master

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: NPM publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
